### ISSUE TITLE
502 Bad Gateway from sql endpoint

### ISSUE THREAD

**Issue by pwaller** [scraperwiki/cobalt#88]
Some datasets are getting a 502 bad gateway for sqlite endpoint queries.

These look something like this in `/var/log/nginx/error.log`:

```
2015/07/08 21:01:31 [error] 959#0: *368 FastCGI sent in stderr: "Traceback (most recent call last):
  File "/opt/dumptruck-web/dumptruck_web.py", line 271, in <module>
    print sql()
  File "/opt/dumptruck-web/dumptruck_web.py", line 167, in sql
    body = json.dumps(body)
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <read-write buffer ptr 0x7fa6b5fe3a30, size 40 at 0x7fa6b5fe39f0> is not JSON serializable" while reading response header from upstream
```

The problem appears to be that dumptruck barfs with the latest python setup if you attempt to view a dataset with BLOB columns.

We were accidentally creating blob columns briefly, but I don't believe that ever made it to production, so I guess these datasets may always have had that issue (though it may only just now be manifesting in this way).

**Comment by pwaller** [comment]
It appears there is at least **one other way** of getting this 502 error:

`upstream sent too big header while reading response header from upstream`

We'll probably need to dig through this tomorrow, since it affects a few datasets.

**Comment by pwaller** [comment]
I've just resolved the latter one with [this commit in salt (private)](https://github.com/scraperwiki/salt-data/commit/f25d4666cd255945942cb444d37f2e642cf27512).

**Comment by pwaller** [comment]
Cracked it! The dumptruck-web had some rubbish in the headers from some debugging we were doing the other day. Checked it out to master and it's fixed.
